database:
  engine: sqlite
  sqlite_path: ./data/quizgen.db
  echo: true

# LLM prompts configuration
prompts:
  # Template for generating questions and answers
  qa_template: >
    Based on the following content, generate a question and its corresponding answer:
    
    Content: {content}
    
    Format your response exactly as:
    Question: [your generated question]
    Answer: [your generated answer]

  # Template for extracting knowledge points
  knowledge_template: >
    Identify the key knowledge point from the following content.
        
    Content: {content}
    
    Important instructions:
    1. Provide ONLY the knowledge point itself without any prefixes like "The key knowledge is" or similar phrases
    2. Keep it concise (1-2 sentences maximum)
    3. Focus on the core concept
    4. Start directly with the knowledge point
    5. Use simple, clear language
    
    Knowledge point:

  # Template for generating single-choice questions
  content_group_question_template: >
    Create a single-choice question based on this content: "{content}"
    
    The question should test the understanding of this specific content.
    
    Format your response exactly as follows:
    Question: [your question here]